### ISSUE TITLE
lxml.etree.XMLSyntaxError

### ISSUE THREAD

**Issue by FredBateman** [Douglas-Christian/iFIT_TCX_Converter#1]
C:\Users\fredb\iFITTCX>v1.0iFITConverter.exe
Traceback (most recent call last):
  File "main.py", line 158, in <module>
  File "main.py", line 144, in main
  File "main.py", line 10, in parse_xml
  File "src\\lxml\\etree.pyx", line 3547, in lxml.etree.parse
  File "src\\lxml\\parser.pxi", line 1952, in lxml.etree._parseDocument
  File "src\\lxml\\parser.pxi", line 1978, in lxml.etree._parseDocumentFromURL
  File "src\\lxml\\parser.pxi", line 1881, in lxml.etree._parseDocFromFile
  File "src\\lxml\\parser.pxi", line 1200, in lxml.etree._BaseParser._parseDocFromFile
  File "src\\lxml\\parser.pxi", line 633, in lxml.etree._ParserContext._handleParseResultDoc
  File "src\\lxml\\parser.pxi", line 743, in lxml.etree._handleParseResult
  File "src\\lxml\\parser.pxi", line 672, in lxml.etree._raiseParseError
  File "D:/downloads.d/HR_90_99.tcx", line 1
lxml.etree.XMLSyntaxError: XML declaration allowed only at the start of the document, line 1, column 16
[10752] Failed to execute script 'main' due to unhandled exception!

C:\Users\fredb\iFITTCX>more HR_90_99.tcx
          <?xml version="1.0" encoding="UTF-8" standalone="yes"?><TrainingCenterDatabase xmlns:ns2="http://www.garmin.com/xmlschemas/UserProfile/v2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns4="http://www.garmin.com/xmlschemas/ProfileExtension/v1" xmlns:ns5="http://www.garmin.com/xmlschemas/ActivityGoals/v1" xmlns:tpx="http://www.garmin.com/xmlschemas/ActivityExtension/v2" xmlns="http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2" xsi:schemaLocation="http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2 http://www.garmin.com/xmlschemas/TrainingCenterDatabasev2.xsd">
            <Activities>
              <Activity Sport="Running"><Notes>Incline</Notes><Id>2024-04-01T11:19:20.677Z</Id><Lap StartTime="2024-04-01T11:19:20.677Z"><Intensity>Active</Intensity><TriggerMethod>Manual</TriggerMethod><TotalTimeSeconds>6145</TotalTimeSeconds><DistanceMeters>9659</DistanceMeters><MaximumSpeed>1.653</MaximumSpeed><AverageHeartRateBpm><Value>91.85887</Value></AverageHeartRateBpm><MaximumHeartRateBpm><Value>109</Value></MaximumHeartRateBpm><Calories>569</Calories><Extensions><LX xmlns="http://www.garmin.com/xmlschemas/ActivityExtension/v2"><AvgSpeed>1.4780000000000002</AvgSpeed></LX></Extensions><Track><Trackpoint><Time>2024-04-01T11:19:20.677Z</Time><DistanceMeters>0</DistanceMeters><AltitudeMeters>0</AltitudeMeters><HeartRateBpm xsi:type="HeartRateInBeatsPerMinute_t"><Value>76</Value></HeartRateBpm><Extensions><TPX xmlns="http://www.garmin.com/xmlschemas/ActivityExtension/v2"><Speed>1.333</Speed><Watts/><RunCadence/></TPX></Extensions></Trackpoint><Trackpoint><Time>2024-04-01T11:19:24.677Z</Time><DistanceMeters>5</DistanceMeters><HeartRateBpm xsi:type="HeartRateInBeatsPerMinute_t"><Value>75</Value></HeartRateBpm><Extensions><TPX xmlns="http://www.garmin.com/xmlschemas/ActivityExtension/v2"><Speed>1.333</Speed><Watts/><RunCadence/></TPX></Extensions></Trackpoint><Trackpoint><Time>2024-04-

[HR_90_99.zip](https://github.com/Douglas-Christian/iFIT_TCX_Converter/files/14843182/HR_90_99.zip)

**Comment by FredBateman** [comment]
This is for an X32i treadmill. I know it says this program is for the S22 bike so if it doesn't work for the treadmill I will understand.

**Comment by Douglas-Christian** [comment]
I will look at it tomorrow. Are you using the executable or the python
scripts from an IDE?

**Comment by FredBateman** [comment]
Found a work-around. 

There are spaces before the first XML text. I deleted the spaces and it worked PERFECTLY!

iFIT sends a TCX file to Strava. 
Export the file from Strava. 
Edit the file removing the spaces.
Run your program.
Import the file into Garmin Connect.
SUCCESS!!!

Thank you very much for the program.

**Comment by Douglas-Christian** [comment]
Pushing a change today that cleans the file of leading spaces prior to
parsing it.

**Comment by FredBateman** [comment]
Thanks! That will make it easier.
